name: Deploy Terraform

on:
  pull_request:
    branches:
      - main  # Trigger when a pull request is opened against the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0  # Specify the Terraform version to use

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1  # Specify your AWS region

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform deployment
      id: plan
      run: terraform plan -out=tfplan

    - name: Check Terraform plan
      if: failure()
      run: echo "Terraform plan failed"; exit 1

    - name: Apply Terraform configuration
      if: success()
      run: terraform apply -auto-approve tfplan

    - name: Post Apply - Display Outputs
      if: success()
      run: terraform output
